### PR TITLE
add tld

### PR DESCRIPTION
**Pull request by zachaysan**

### CODE REVIEW

**Comment by shazow** [comment]
Thankies. Gonna let this stew a bit :leaves:

**Comment by shazow** [comment]
@zachaysan :heart: never personally needed the tld to this day, but I'm sure it's a better fit for your dotfiles. :)

**Comment by zachaysan** [comment]
Haha, I use it from time to time. The biggest thing I took from your repo was `up`.

**Comment by shazow** [comment]
You might enjoy the recent addition of `scd` (and `findsrc`), probably my most-used helper today: https://github.com/shazow/dotfiles/blob/master/helpers.bash#L32

It basically obsoleted `go` for me.

**Pull request closed without merging**
